---
name: walleye
description: A Wallpaper App
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  flutter_bloc: ^6.0.6
  google_fonts: ^1.1.0
  cached_network_image: ^2.3.2+1
  sqflite: ^1.3.1+1
  font_awesome_flutter: ^8.10.0
  flutter_share: ^1.0.2+1
  flutter_share_me: ^0.9.1
  flutter_cache_manager: ^1.4.2
  photo_view: ^0.10.2
  wallpaper_manager: ^1.0.10
  simple_speed_dial: ^0.1.2
  toast: ^0.1.5
  animations: ^1.1.2
  flutter_downloader: ^1.5.1
  easy_permission_validator: ^2.0.1
  ext_storage: ^1.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
